blogpost/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blogpost.apps import BlogpostConfig
from blogpost.views import BlogPostListView, BlogPostDetailView, BlogPostCreateView, BlogPostDeleteView, BlogPostUpdateView

app_name = BlogpostConfig.name

urlpatterns = [
    path('list/', BlogPostListView.as_view(), name='list'),
    path('blogpost/<int:pk>', cache_page(60)(BlogPostDetailView.as_view()), name='blogpost'),
    path('create/', BlogPostCreateView.as_view(), name='create'),
    path('delete/<int:pk>', BlogPostDeleteView.as_view(), name='delete'),
    path('edit/<int:pk>', BlogPostUpdateView.as_view(), name='edit'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='products')),
    path('blogpost', include('blogpost.urls', namespace='blogposts')),
    path('users/', include('users.urls', namespace='users')),
    path('mailing/', include('mailing.urls', namespace='mailing')),
    path('select2/', include('django_select2.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from main.apps import MainConfig
from main.views import ProductDetailView, ProductListView, ProductCreateView, ProductDeleteView, ProductUpdateView

app_name = MainConfig.name

urlpatterns = [
    path('', ProductListView.as_view(), name='index'),
    path('product/<int:pk>', cache_page(10)(ProductDetailView.as_view()), name='product'),
    path('create/', ProductCreateView.as_view(), name='create'),
    path('delete/<int:pk>', ProductDeleteView.as_view(), name='delete'),
    path('edit/<int:pk>', ProductUpdateView.as_view(), name='edit'),
]

blogpost/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class BlogPost(models.Model):
    title = models.CharField(max_length=100, verbose_name='заголовок')
    content = models.TextField(verbose_name='содержимое', **NULLABLE)
    preview = models.ImageField(upload_to='blogpost/', verbose_name='превью', **NULLABLE)
    slug = models.CharField(max_length=100, verbose_name='slug', **NULLABLE)
    date_of_creation = models.DateTimeField(verbose_name='дата создания')
    is_published = models.BooleanField(default=True, verbose_name='опубликовано')
    views_count = models.IntegerField(default=0, verbose_name='просмотры')

    def __str__(self):
        return f'{self.title}: {self.content}'

    class Meta:
        verbose_name = 'Блог пост'
        verbose_name_plural = 'Блог посты'
        ordering = ('id',)

blogpost/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.utils import timezone
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from pytils.translit import slugify

from blogpost.models import BlogPost


class BlogPostListView(ListView):
    model = BlogPost

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Блог'
        return context


class BlogPostCreateView(CreateView):
    model = BlogPost
    fields = ('title', 'content', 'preview', 'is_published')
    success_url = reverse_lazy('blogposts:list')

    def form_valid(self, form):
        form.instance.date_of_creation = timezone.now()
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()

        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Создание поста'
        return context


class BlogPostDetailView(DetailView):
    model = BlogPost

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class BlogPostUpdateView(UpdateView):
    model = BlogPost
    fields = ('title', 'content', 'preview', 'is_published')

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blogposts:blogpost', args=[self.kwargs.get('pk')])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Редактирование поста'
        return context


class BlogPostDeleteView(DeleteView):
    model = BlogPost
    success_url = reverse_lazy('blogposts:list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Удаление поста'
        return context

blogpost/templates/blogpost/blogpost_confirm_delete.html
{% extends 'main/base.html' %}
{% block content %}
<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <p class="fs-5">Вы уверены что хотите удалить пост "{{ object.title }}"?</p>
                            <button type="submit" class="btn btn-danger">Подтвердить</button>
                            <a href="{% url 'blogposts:list' %}" class="btn btn-warning">Отмена</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blogpost/templates/blogpost/blogpost_detail.html
{% extends 'main/base.html' %}
{% load media_tags %}
{% load custom_filters %}
{%block content %}
<div class="container-fluid">
    <div class="image-container" style="overflow:hidden; height:45vh">
        <div class="d-flex justify-content-center" style="transform:translateY(-15%)">
            <img src="{% mediapath object.preview %}" class="img-fluid" alt=" {{ object.title }}"/>
        </div>
    </div>
</div>
<div class="container mb-5" style="margin-top:3vh;">
    <div class="row justify-content-between">
        <div class="col-4">
            <h2 class="text-nowrap">{{ object.title }} ({{ object.slug }})</h2>
            {% if object.is_published == True %}
            <div class="badge bg-success fs-5 text-wrap mb-2">Опубликовано</div>
            {% else %}
            <div class="badge bg-warning fs-5 text-wrap mb-2">Не опубликовано</div>
            {% endif %}
        </div>
        <div class="col-4 text-end">
            <div class="btn-group mt-2">
                <div class="btn-group">
                    <a href="{% url 'blogpost:edit' object.pk %}" type="button"
                       class="btn btn-outline-primary">Редактировать</a>
                    <a href="{% url 'blogpost:delete' object.pk %}" type="button"
                       class="btn btn-outline-danger">Удалить</a>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <p class="fs-5"> {{ object.content }} </p>
    <div class="footer">
        <p class="fs-5 text-secondary"> Просмотры: {{ object.views_count }}</p>

    </div>

</div>
<div class="container" style="margin-top:10vh;">
    <div class="row justify-content-between">
        <div class="col-4">
            <p class="text-nowrap text-secondary">Дата создания: {{ object.date_of_creation }}</p>
        </div>
    </div>
</div>
{% endblock %}

blogpost/templates/blogpost/blogpost_form.html
{% extends 'main/base.html' %}
{% load media_tags %}
{% load custom_filters %}
{% block content %}
<section class="text-center container">
    <div class="row py-lg-5">
        <div class="col-md-8 mx-auto">
            <h1 class="fw-light">{{ title }}</h1>
        </div>
    </div>
</section>
<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    {% if object %}
                    <div class="card-header">Редактирование поста</div>
                    {% else %}
                    <div class="card-header">Создание поста</div>
                    {% endif %}
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-success">
                                {% if object %}
                                Сохранить
                                {% else %}
                                Создать
                                {% endif %}
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blogpost/templates/blogpost/blogpost_list.html
{% extends 'main/base.html' %}
{% load media_tags %}
{% load custom_filters %}
{% block content %}
<section class="text-center container">
    <div class="row py-lg-5">
        <div class="col-md-8 mx-auto">
            <h1 class="fw-light">{{ title }}</h1>
            <p>Здесь Вы можете создать свой пост о чём угодно!</p>
        </div>
    </div>
</section>

<div class="album py-5 bg-light">
    <div class="container">
        <div class="col-12 mb-5">
            <a class="btn btn-outline-secondary" href="{% url 'blogposts:create' %}">Добавить пост</a>
        </div>
        <div class="row">
            {% for object in object_list %}
            {% if object.is_published == True %}
                <div class="card mb-4 box-shadow">
                    <img src="{% mediapath object.preview %}" class="card-img-top" alt="{{ object.name }}" style="object-fit: cover; height: 20vh"/>
                    <div class="card-body">
                        <h4><a href="{% url 'blogposts:blogpost' object.pk %}" class="card-title"> {{ object.title }}</a></h4>
                        <p class="card-text">{{ object.content|truncatechars:100 }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="col">
                                <div class="btn-group">
                                    <a href="{% url 'blogposts:edit' object.pk %}" type="button"
                                       class="btn btn-sm btn-outline-primary">Редактировать</a>
                                    <a href="{% url 'blogposts:delete' object.pk %}" type="button"
                                       class="btn btn-sm btn-outline-danger">Удалить</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}