config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='products')),
    path('blogpost', include('blogpost.urls', namespace='blogposts')),
    path('users/', include('users.urls', namespace='users')),
    path('mailing/', include('mailing.urls', namespace='mailing')),
    path('select2/', include('django_select2.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from main.apps import MainConfig
from main.views import ProductDetailView, ProductListView, ProductCreateView, ProductDeleteView, ProductUpdateView

app_name = MainConfig.name

urlpatterns = [
    path('', ProductListView.as_view(), name='index'),
    path('product/<int:pk>', cache_page(10)(ProductDetailView.as_view()), name='product'),
    path('create/', ProductCreateView.as_view(), name='create'),
    path('delete/<int:pk>', ProductDeleteView.as_view(), name='delete'),
    path('edit/<int:pk>', ProductUpdateView.as_view(), name='edit'),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, EmailConfirmationSentView, UserConfirmEmailView, EmailConfirmedView, \
    EmailConfirmationFailedView, PasswordResetView, UserLoginView

app_name = UsersConfig.name


urlpatterns = [
    path('', UserLoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('email-confirmation-sent', EmailConfirmationSentView.as_view(), name='email_confirmation_sent'),
    path('confirm-email/<str:uid64>/<str:token>/', UserConfirmEmailView.as_view(), name='confirm_email'),
    path('email-confirmed/', EmailConfirmedView.as_view(), name='email_confirmed'),
    path('confirm-email-failed/', EmailConfirmationFailedView.as_view(), name='email_confirmation_failed'),
    path('password-reset/', PasswordResetView.as_view(), name='password_reset')
]

main/models.py
from django.db import models

from users.models import User

NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name='наименование')
    description = models.TextField(verbose_name='описание', **NULLABLE)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ('id',)


class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name='наименование')
    description = models.TextField(verbose_name='описание', null=True)
    preview = models.ImageField(upload_to='products/', verbose_name='изображение (превью)', **NULLABLE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='категория')
    price = models.IntegerField(verbose_name='цена за покупку')
    date_of_creation = models.DateTimeField(verbose_name='дата создания')
    date_of_correction = models.DateTimeField(verbose_name='дата последнего изменения', **NULLABLE)

    views_count = models.IntegerField(default=0, verbose_name='просмотры')
    is_published = models.BooleanField(default=True, verbose_name='опубликован')
    slug = models.CharField(max_length=150, verbose_name='slug', **NULLABLE)

    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='пользователь', **NULLABLE)

    def __str__(self):
        return f'{self.name} {self.category} {self.price}'

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
        ordering = ('id',)


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='продукт')
    version_number = models.IntegerField(verbose_name='номер версии')
    version_name = models.CharField(max_length=150, verbose_name='название версии')
    is_active = models.BooleanField(default=True, verbose_name='активно')

    def __str__(self):
        return f'{self.version_name} {self.version_number}'

    class Meta:
        verbose_name = 'Версия'
        verbose_name_plural = 'Версии'
        ordering = ('version_number',)

main/forms.py
from django import forms


from main.models import Product, Version


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field.widget, (forms.TextInput, forms.Textarea)):
                field.widget.attrs.update({'class': 'form-control'})
            elif isinstance(field.widget, forms.CheckboxInput):
                field.widget.attrs.update({'class': 'form-check-input'})
            else:
                field.widget.attrs.update({'class': 'form-select'})


class ProductForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Product
        fields = ('name', 'description', 'preview', 'price', 'category', 'is_published')

    def clean_name(self):
        cleaned_data = self.cleaned_data['name']
        forbidden_names = ['казино',
                           'криптовалюта',
                           'крипта',
                           'биржа',
                           'дешево',
                           'бесплатно',
                           'обман',
                           'полиция',
                           'радар'
                           ]
        for name in forbidden_names:
            if name.lower() in cleaned_data.lower():
                raise forms.ValidationError('Запрещенный продукт')

        return cleaned_data


class VersionForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Version
        fields = '__all__'

main/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.forms import inlineformset_factory
from django.http import HttpResponseForbidden
from django.urls import reverse_lazy, reverse
from django.utils import timezone
from django.views.decorators.cache import cache_page
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from pytils.translit import slugify
from django.core.cache import cache

from config import settings
from main.forms import ProductForm, VersionForm
from main.models import Product, Version


class ProductListView(ListView):
    model = Product

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Продукты'
        return context


class ProductDetailView(DetailView):
    model = Product

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class ProductCreateView(CreateView):
    model = Product
    fields = ('name', 'description', 'preview', 'price', 'category')
    success_url = reverse_lazy('products:index')

    def form_valid(self, form):
        form.instance.date_of_creation = timezone.now()
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.name)
            new_mat.save()
            new_mat.user = self.request.user

        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Создание продукта'
        return context


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    success_url = reverse_lazy('products:index')
    login_url = reverse_lazy('users:login')
    redirect_field_name = 'redirect_to'

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()

        if self.object.user != self.request.user:
            return HttpResponseForbidden("Вы не можете удалить продукт другого пользователя.")

        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Удаление продукта'
        return context


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    login_url = reverse_lazy('users:login')
    redirect_field_name = 'redirect_to'

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()

        if self.object.user != self.request.user:
            return HttpResponseForbidden("Вы не можете удалить продукт другого пользователя.")

        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.name)
            new_mat.save()
            form.instance.date_of_correction = timezone.now()

        formset = self.get_context_data()['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('products:product', args=[self.kwargs.get('pk')])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Редактирование продукта'
        SubjectFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            context['formset'] = SubjectFormset(self.request.POST, instance=self.object)
        else:
            context['formset'] = SubjectFormset(instance=self.object)
        return context

main/templates/main/base.html
<!doctype html>
{% load static %}
{% load media_tags %}
{% load custom_filters %}
<html lang="en" data-bs-theme="auto">
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.112.5">
    <title>{{ title }}</title>


    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet"
          integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">

    <!-- Favicons -->
    <meta name="theme-color" content="#712cf9">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        width: 100%;
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }

      .btn-bd-primary {
        --bd-violet-bg: #712cf9;
        --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

        --bs-btn-font-weight: 600;
        --bs-btn-color: var(--bs-white);
        --bs-btn-bg: var(--bd-violet-bg);
        --bs-btn-border-color: var(--bd-violet-bg);
        --bs-btn-hover-color: var(--bs-white);
        --bs-btn-hover-bg: #6528e0;
        --bs-btn-hover-border-color: #6528e0;
        --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
        --bs-btn-active-color: var(--bs-btn-hover-color);
        --bs-btn-active-bg: #5a23c8;
        --bs-btn-active-border-color: #5a23c8;
      }
      .bd-mode-toggle {
        z-index: 1500;
      }











    </style>


</head>
<body>
<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
    <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
    </symbol>
    <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
    </symbol>
    <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
    </symbol>
    <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
    </symbol>
</svg>

<div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
    <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center"
            id="bd-theme"
            type="button"
            aria-expanded="false"
            data-bs-toggle="dropdown"
            aria-label="Toggle theme (auto)">
        <svg class="bi my-1 theme-icon-active" width="1em" height="1em">
            <use href="#circle-half"></use>
        </svg>
        <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
    </button>
    <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light"
                    aria-pressed="false">
                <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em">
                    <use href="#sun-fill"></use>
                </svg>
                Light
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark"
                    aria-pressed="false">
                <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em">
                    <use href="#moon-stars-fill"></use>
                </svg>
                Dark
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto"
                    aria-pressed="true">
                <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em">
                    <use href="#circle-half"></use>
                </svg>
                Auto
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
    </ul>
</div>


<header data-bs-theme="dark">
    <div class="collapse text-bg-dark" id="navbarHeader">
        <div class="container">
            <div class="row">
                <div class="col-sm-3 col-md-7 py-4">
                    {% if user.is_authenticated %}
                    <div class="profile">
                        <div class="circle">
                            <img src="{% mediapath user.avatar %}" alt="Аватар">
                        </div>
                        <div class="col-7">
                            <div class="card ms-3 border-0 bg-dark">
                                <div class="card-title fs-4">Вы вошли как:</div>
                                    <div class="card-text">{{ user.first_name }} {{user.last_name }}</div>
                                    <div class="card-text">{{ user.email }}</div>
                            </div>
                        </div>
                    </div>
                    {% else %}
                    <h4>Вход не выполнен</h4>
                    <p><a href="{% url 'users:register' %}" class="text-white">Зарегистрироваться</a></p>
                    <p>Вы уже зарегистрированы? <a href="{% url 'users:login' %}" class="text-white">Войти</a></p>
                    {% endif %}
                </div>
                {% include 'main/includes/inc_main_menu.html' %}
            </div>
        </div>
    </div>
    <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container">
            <a href="{% url 'main:index' %}" class="navbar-brand d-flex align-items-center">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor"
                     stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2"
                     viewBox="0 0 24 24">
                    <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/>
                    <circle cx="12" cy="13" r="4"/>
                </svg>
                <strong>Продукты</strong>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader"
                    aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </div>
</header>

<main>

    {% block content %}
    {% endblock %}

</main>

<footer class="text-body-secondary py-5">
    <div class="container">
        <p class="float-end mb-1">
            <a href="#">Back to top</a>
        </p>
        <p class="mb-1">&copy; 2023 - {% now 'Y' %}</p>
    </div>
</footer>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"
        integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
        crossorigin="anonymous"></script>

</body>
</html>

main/templates/main/product_confirm_delete.html
{% extends 'main/base.html' %}

{% block content %}
{% include 'main/includes/inc_image.html' %}
<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <p class="fs-5">Вы уверены что хотите удалить продукт "{{ object.name }}"?</p>
                            <button type="submit" class="btn btn-danger">Подтвердить</button>
                            <a href="{% url 'products:index' %}" class="btn btn-warning">Отмена</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/product_detail.html
{% extends 'main/base.html' %}
{% load media_tags %}
{% load custom_filters %}
{% block content %}
<div class="container-fluid">
    <div class="image-container" style="overflow:hidden; height:45vh">
        <div class="d-flex justify-content-center" style="transform:translateY(-15%)">
            <img src="{% mediapath object.preview %}" class="img-fluid" alt=" {{ product_detail.name }}"/>
        </div>
    </div>
</div>
<div class="container mb-5" style="margin-top:3vh;">
    <div class="row justify-content-between">
        <div class="col-4">
            <h2 class="text-nowrap">{{ object.name }} ({{ object.slug }})</h2>
            {% if object.is_published == True %}
            <div class="badge bg-success fs-5 text-wrap mb-2">Опубликовано</div>
            {% else %}
            <div class="badge bg-warning fs-5 text-wrap mb-2">Не опубликовано</div>
            {% endif %}
        </div>
        <div class="col-4 text-end">
            <div class="badge bg-secondary fs-5 text-wrap" style="width: 20rem;">{{ object.category }}</div>
            <div class="btn-group mt-2">
                <div class="btn-group">
                    {% if user == object.user %}
                    <a href="{% url 'products:edit' object.pk %}" type="button"
                       class="btn btn-outline-primary">Редактировать</a>
                    <a href="{% url 'products:delete' object.pk %}" type="button"
                       class="btn btn-outline-danger">Удалить</a>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="w-100">
            <div class="col-4">
                <h4 class="text-body-secondary">{{ object.price|intspace }} руб.</h4>
            </div>
        </div>
        <div class="col-4"></div>
    </div>
</div>
<div class="container">
    <div class="header">
        <h3 class="text"> Описание</h3>
    </div>
    <p class="fs-5"> {{ object.description }} </p>
    <div class="footer">
        <p class="fs-5 text-secondary"> Просмотры: {{ object.views_count }}</p>
        <p class="fs-5 text-secondary"> Автор: {{ object.user.first_name }} {{ object.user.last_name }} ({{ object.user.email }})</p>
    </div>

</div>
<div class="container" style="margin-top:10vh;">
    <div class="row justify-content-between">
        <div class="col-4">
            <p class="text-nowrap text-secondary">Дата создания: {{ object.date_of_creation }}</p>
        </div>
    </div>
    <div class="w-100">
        <div class="col-4">
            {% if object.date_of_correction == None %}
            <p class="text-nowrap text-secondary">Дата последнего редактирования: -</p>
            {% else %}
            <p class="text-nowrap text-secondary">Дата последнего редактирования: {{ object.date_of_correction }}</p>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/product_form.html
{% extends 'main/base.html' %}
{% load media_tags %}
{% load custom_filters %}
{% block content %}
{% if object %}
{% include 'main/includes/inc_image.html' %}
<form method="post" enctype="multipart/form-data">
    <div class="album py-5 bg-light">
        <div class="container">
            <div class="row">
                <div class="col-6">
                    <div class="card">
                        {% if object %}
                        <div class="card-header">Редактирование продукта</div>
                        {% else %}
                        <div class="card-header">Создание продукта</div>
                        {% endif %}
                        <div class="card-body">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-success">
                                {% if object %}
                                Сохранить
                                {% else %}
                                Создать
                                {% endif %}
                            </button>

                        </div>
                    </div>
                </div>
                <div class="col-6">
                    <div class="card">
                        {% if object %}
                        <div class="card-header">Редактирование продукта</div>
                        {% else %}
                        <div class="card-header">Создание продукта</div>
                        {% endif %}
                        <div class="card-body">
                            {{ formset.management_form }}
                                {% for form in formset.forms %}
                                {{ form.as_p }}
                                    {% if not forloop.last %}
                                        <hr>
                                    {% endif %}
                                {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
{% else %}
<section class="text-center container">
    <div class="row py-lg-5">
        <div class="col-md-8 mx-auto">
            <h1 class="fw-light">{{ title }}</h1>
        </div>
    </div>
</section>
<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    {% if object %}
                    <div class="card-header">Редактирование продукта</div>
                    {% else %}
                    <div class="card-header">Создание продукта</div>
                    {% endif %}
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-success">
                                {% if object %}
                                Сохранить
                                {% else %}
                                Создать
                                {% endif %}
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

main/templates/main/product_list.html
{% extends 'main/base.html' %}
{% load media_tags %}
{% load custom_filters %}
{% block content %}
<section class="text-center container">
    <div class="row py-lg-5">
        <div class="col-md-8 mx-auto">
            <h1 class="fw-light">{{ title }}</h1>
            <p>Добро пожаловать в наш интернет-магазин электроники, звуковых систем и товаров для здоровья кожи!</p>
            <p>Здесь вы найдете самые инновационные и качественные товары, которые обеспечат вас удивительным опытом и
                подарят ощущение полного комфорта.</p>
        </div>
    </div>
</section>

<div class="album py-5 bg-light">
    <div class="container">
        <div class="col-12 mb-5">
            <a class="btn btn-outline-secondary" href="{% url 'products:create' %}">Добавить продукт</a>
        </div>
        <div class="row justify-content-center">
            {% for object in object_list %}
            {% if object.is_published == True %}
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <img src="{% mediapath object.preview %}" class="card-img-top" alt="{{ object.name }}"
                         style="object-fit: cover; height: 20vh"/>
                    <div class="card-body">
                        <h4><a href="{% url 'products:product' object.pk %}" class="card-title"> {{ object.name }}</a>
                        </h4>
                        <div class="card-text">
                            <p>{{ object.description|truncatechars:100 }}</p>
                        </div>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="col">
                                <h6 class="card-subtitle mb-3 text-body-secondary">{{ object.price|intspace }} руб.</h6>
                                <div class="btn-group">
                                    {% if user == object.user %}
                                    <a href="{% url 'products:edit' object.pk %}" type="button"
                                       class="btn btn-sm btn-outline-primary">Редактировать</a>
                                    <a href="{% url 'products:delete' object.pk %}" type="button"
                                       class="btn btn-sm btn-outline-danger">Удалить</a>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        {% if object.version_set.exists %}
                        <a>Версия продукта:</a>
                        {% for version in object.version_set.all %}
                        {% if version.is_active == True %}
                        <a>{{ version.version_number }}</a>
                        {% endif %}
                        {% endfor %}
                        {% else %}
                        <a>У этого продукта нет версий.</a>
                        {% endif %}
                    </div>
                </div>
            </div>
            {% endif %}
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}