config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='products')),
    path('blogpost', include('blogpost.urls', namespace='blogposts')),
    path('users/', include('users.urls', namespace='users')),
    path('mailing/', include('mailing.urls', namespace='mailing')),
    path('select2/', include('django_select2.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from . import views

from mailing.apps import MailingConfig
from mailing.views import NewsletterListView, NewsletterCreateView, NewsletterUpdateView, NewsletterDetailView, \
    NewsletterDeleteView, MessageCreateView, MessageListView, MessageDetailView, MessageUpdateView, MessageDeleteView, \
    ClientCreateView, ClientListView, ClientDetailView, ClientUpdateView, ClientDeleteView

app_name = MailingConfig.name

urlpatterns = [
    path('', NewsletterListView.as_view(), name='index'),
    path('create/', NewsletterCreateView.as_view(), name='create'),
    path('edit/<int:pk>', NewsletterUpdateView.as_view(), name='edit'),
    path('newsletter/<int:pk>', NewsletterDetailView.as_view(), name='newsletter'),
    path('delete/<int:pk>', NewsletterDeleteView.as_view(), name='delete'),
    path('newsletter/<int:pk>/start/', views.start_newsletter, name='start_newsletter'),
    path('message/create/', MessageCreateView.as_view(), name='message_create'),
    path('message/', MessageListView.as_view(), name='message_list'),
    path('message/<int:pk>', cache_page(10)(MessageDetailView.as_view()), name='message_detail'),
    path('message/edit/<int:pk>', MessageUpdateView.as_view(), name='message_edit'),
    path('message/delete/<int:pk>', MessageDeleteView.as_view(), name='message_delete'),
    path('client/create/', ClientCreateView.as_view(), name='client_create'),
    path('client/', ClientListView.as_view(), name='client_list'),
    path('client/<int:pk>', cache_page(10)(ClientDetailView.as_view()), name='client_detail'),
    path('client/edit/<int:pk>', ClientUpdateView.as_view(), name='client_edit'),
    path('client/delete/<int:pk>', ClientDeleteView.as_view(), name='client_delete'),
]

main/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from main.apps import MainConfig
from main.views import ProductDetailView, ProductListView, ProductCreateView, ProductDeleteView, ProductUpdateView

app_name = MainConfig.name

urlpatterns = [
    path('', ProductListView.as_view(), name='index'),
    path('product/<int:pk>', cache_page(10)(ProductDetailView.as_view()), name='product'),
    path('create/', ProductCreateView.as_view(), name='create'),
    path('delete/<int:pk>', ProductDeleteView.as_view(), name='delete'),
    path('edit/<int:pk>', ProductUpdateView.as_view(), name='edit'),
]

mailing/models.py
from django.db import models
from django.contrib.auth import get_user_model
from main.models import NULLABLE


class Client(models.Model):
    email = models.EmailField(unique=True, verbose_name='контактная почта')
    first_name = models.CharField(max_length=100, verbose_name='имя')
    last_name = models.CharField(max_length=100, verbose_name='фамилия')
    middle_name = models.CharField(max_length=100, verbose_name='отчество')
    comment = models.TextField(blank=True, verbose_name='комментарий')
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, verbose_name='автор', **NULLABLE)

    def __str__(self):
        return str(self.email) + ": " + self.last_name[:1] + "." + self.first_name[:1] + "." + self.middle_name[:1] + "."

    class Meta:
        verbose_name = "Клиент"
        verbose_name_plural = "Клиенты"
        ordering = ('first_name',)


class Message(models.Model):
    subject = models.CharField(max_length=255, verbose_name='тема')
    body = models.TextField(verbose_name='сообщение')
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, verbose_name='автор', **NULLABLE)

    def __str__(self):
        return f"{self.subject}"

    class Meta:
        verbose_name = "Сообщение"
        verbose_name_plural = "Сообщения"
        ordering = ('newsletter',)


class Newsletter(models.Model):
    DAILY = "ED"
    WEEKLY = "EW"
    MONTHLY = "EM"
    CREATED = "CR"
    STARTED = "ST"
    COMPLETED = "CMP"
    client = models.ManyToManyField(Client, verbose_name='клиент')
    time = models.TimeField(verbose_name='время рассылки')
    message = models.ForeignKey(Message, on_delete=models.CASCADE, verbose_name='сообщение', **NULLABLE)
    frequency_choices = [
        (DAILY, "Раз в день"),
        (WEEKLY, "Раз в неделю"),
        (MONTHLY, "Раз в месяц"),
    ]
    frequency = models.CharField(max_length=20, choices=frequency_choices, verbose_name='частота рассылки')
    status_choices = [
        (CREATED, "Создана"),
        (STARTED, "Запущена"),
        (COMPLETED, "Заврешена"),
    ]
    status = models.CharField(default=CREATED, max_length=10, choices=status_choices, verbose_name='статус рассылки')
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, verbose_name='автор')

    def __str__(self):
        return f"{self.client}: {self.time}, {self.status}"

    class Meta:
        verbose_name = "Рассылка"
        verbose_name_plural = "Рассылки"
        ordering = ('status',)


class DeliveryLog(models.Model):
    SUCCESS = "SC"
    FAILED = "FD"
    message = models.ForeignKey(Message, on_delete=models.CASCADE, verbose_name='сообщение')
    timestamp = models.DateTimeField(auto_now_add=True)
    status_choices = [
        (SUCCESS, 'Успешно'),
        (FAILED, 'Провалено')
    ]
    status = models.CharField(max_length=15, choices=status_choices, verbose_name='статус')
    server_response = models.TextField(verbose_name='ответ от сервера', **NULLABLE)

    def __str__(self):
        return f"{self.timestamp}: {self.status}"

    class Meta:
        verbose_name = "Лог рассылки"
        verbose_name_plural = "Логи рассылки"
        ordering = ('status',)


class Meta:
    permissions = [
        ("can_create_newsletters", "Может создавать рассылки"),
    ]

mailing/forms.py
from django import forms


from mailing.models import Newsletter, Client, Message


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field.widget, (forms.TextInput, forms.Textarea)):
                field.widget.attrs.update({'class': 'form-control'})
            elif isinstance(field.widget, forms.CheckboxSelectMultiple):
                field.widget.attrs.update({'class': 'form-check-input'})
            else:
                field.widget.attrs.update({'class': 'form-select'})


class NewsletterForm(StyleFormMixin, forms.ModelForm):
    client = forms.ModelMultipleChoiceField(
        required=True,
        queryset=Client.objects.all(),
    )

    class Meta:
        model = Newsletter
        fields = ('client', 'time', 'message', 'frequency')


class ClientForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Client
        fields = ('email', 'first_name', 'last_name', 'middle_name', 'comment',)


class MessageForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Message
        fields = ('subject', 'body',)

mailing/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import HttpResponseForbidden, JsonResponse
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.decorators.http import require_POST
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView
from django.contrib.auth.decorators import user_passes_test

from blogpost.models import BlogPost
from mailing.forms import NewsletterForm, MessageForm, ClientForm
from mailing.models import Newsletter, Message, Client


class NewsletterListView(ListView):
    model = Newsletter
    template_name = 'mailing/newsletter/newsletter_list.html'

    def get_queryset(self):
        queryset = super().get_queryset()

        if is_moderator(self.request.user):
            return queryset

        return queryset.filter(author=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        total_mailings = Newsletter.objects.count()
        active_mailings = Newsletter.objects.filter(status=Newsletter.STARTED).count()
        unique_clients = Client.objects.count()
        random_articles = BlogPost.objects.order_by('?')[:3]

        context['title'] = 'Рассылки'
        context['total_mailings'] = total_mailings
        context['active_mailings'] = active_mailings
        context['unique_clients'] = unique_clients
        context['random_articles'] = random_articles
        return context


class NewsletterCreateView(PermissionRequiredMixin, CreateView):
    model = Newsletter
    template_name = 'mailing/newsletter/newsletter_form.html'
    form_class = NewsletterForm
    success_url = reverse_lazy('mailing:index')
    permission_required = 'mailing.can_create_newsletter'

    def form_valid(self, form):
        if form.is_valid():
            new_newsletter = form.save(commit=False)
            new_newsletter.author = self.request.user
            new_newsletter.save()

        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Создание рассылки'
        return context


class NewsletterUpdateView(LoginRequiredMixin, UpdateView):
    model = Newsletter
    template_name = 'mailing/newsletter/newsletter_form.html'
    form_class = NewsletterForm
    login_url = reverse_lazy('users:login')
    redirect_field_name = 'redirect_to'

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()

        if self.object.author != self.request.user:
            return HttpResponseForbidden("Вы не можете редактировать рассылку другого пользователя.")

        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('mailing:newsletter', args=[self.kwargs.get('pk')])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Редактирование рассылки'
        return context


class NewsletterDetailView(DetailView):
    model = Newsletter
    template_name = 'mailing/newsletter/newsletter_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['allowed_statuses'] = [Newsletter.CREATED, Newsletter.STARTED]
        return context


class NewsletterDeleteView(LoginRequiredMixin, DeleteView):
    model = Newsletter
    template_name = 'mailing/newsletter/newsletter_confirm_delete.html'
    success_url = reverse_lazy('mailing:index')
    login_url = reverse_lazy('users:login')
    redirect_field_name = 'redirect_to'

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()

        if self.object.author != self.request.user:
            return HttpResponseForbidden("Вы не можете удалить рассылку другого пользователя.")

        return super().dispatch(request, *args, **kwargs)


class MessageCreateView(CreateView):
    model = Message
    template_name = 'mailing/message/message_form.html'
    form_class = MessageForm
    success_url = reverse_lazy('mailing:message_list')

    def form_valid(self, form):
        if form.is_valid():
            new_newsletter = form.save(commit=False)
            new_newsletter.author = self.request.user
            new_newsletter.save()

        return super().form_valid(form)


class MessageListView(ListView):
    model = Message
    template_name = 'mailing/message/message_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Сообщения'
        return context


class MessageDetailView(DetailView):
    model = Message
    template_name = 'mailing/message/message_detail.html'


class MessageUpdateView(LoginRequiredMixin, UpdateView):
    model = Message
    form_class = MessageForm
    template_name = 'mailing/message/message_form.html'
    login_url = reverse_lazy('users:login')
    redirect_field_name = 'redirect_to'

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()

        if self.object.author != self.request.user:
            return HttpResponseForbidden("Вы не можете редактировать сообщение другого пользователя.")

        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('mailing:message_detail', args=[self.kwargs.get('pk')])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Редактирование сообщения'
        return context


class MessageDeleteView(LoginRequiredMixin, DeleteView):
    model = Message
    template_name = 'mailing/message/message_confirm_delete.html'
    success_url = reverse_lazy('mailing:message_list')
    login_url = reverse_lazy('users:login')
    redirect_field_name = 'redirect_to'

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()

        if self.object.author != self.request.user:
            return HttpResponseForbidden("Вы не можете удалить сообщение другого пользователя.")

        return super().dispatch(request, *args, **kwargs)


class ClientCreateView(CreateView):
    model = Client
    template_name = 'mailing/client/client_form.html'
    form_class = ClientForm
    success_url = reverse_lazy('mailing:client_list')


class ClientListView(ListView):
    model = Client
    template_name = 'mailing/client/client_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Клиенты'
        return context


class ClientDetailView(DetailView):
    model = Client
    template_name = 'mailing/client/client_detail.html'


class ClientUpdateView(LoginRequiredMixin, UpdateView):
    model = Client
    form_class = ClientForm
    template_name = 'mailing/client/client_form.html'
    login_url = reverse_lazy('users:login')
    redirect_field_name = 'redirect_to'

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()

        if self.object.author != self.request.user:
            return HttpResponseForbidden("Вы не можете редактировать клиентов другого пользователя.")

        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('mailing:client_detail', args=[self.kwargs.get('pk')])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Редактирование клиента'
        return context


class ClientDeleteView(LoginRequiredMixin, DeleteView):
    model = Client
    template_name = 'mailing/client/client_confirm_delete.html'
    success_url = reverse_lazy('mailing:client_list')
    login_url = reverse_lazy('users:login')
    redirect_field_name = 'redirect_to'

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()

        if self.object.author != self.request.user:
            return HttpResponseForbidden("Вы не можете удалить клиента другого пользователя.")

        return super().dispatch(request, *args, **kwargs)


def is_moderator(user):
    return user.groups.filter(name="Модератор").exists()


@user_passes_test(is_moderator)
@require_POST
def start_newsletter(request, pk):
    if request.user.is_authenticated:
        newsletter = Newsletter.objects.get(pk=pk)
        if newsletter.status == Newsletter.CREATED:
            newsletter.status = Newsletter.STARTED
        elif newsletter.status == Newsletter.STARTED:
            newsletter.status = Newsletter.CREATED
        newsletter.save()
        return JsonResponse({'status': newsletter.get_status_display()})

mailing/templates/mailing/newsletter/newsletter_confirm_delete.html
{% extends 'main/base.html' %}

{% block content %}
<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <p class="fs-5">Вы уверены что хотите удалить рассылку "{{ object.message.subject }}"?</p>
                            <button type="submit" class="btn btn-danger">Подтвердить</button>
                            <a href="{% url 'mailing:index' %}" class="btn btn-warning">Отмена</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/newsletter/newsletter_detail.html
{% extends 'main/base.html' %}
{% load media_tags %}
{% load custom_filters %}
{% block content %}
<div class="container mb-5" style="margin-top:3vh;">
    <div class="row justify-content-between">
        <div class="col-4">
            <a href="{% url 'mailing:index' %}" class="btn btn-outline-secondary mb-4">К списку рассылок</a>
            <h2 class="text-nowrap">{{ object.message.subject }}</h2>
            {% if object.status == "CR" %}
            <div class="badge bg-secondary fs-5 text-wrap mb-2">Создана</div>
            {% elif object.status == "ST" %}
            <div class="badge bg-warning fs-5 text-wrap mb-2">Запущена</div>
            {% elif object.status == "CMP" %}
            <div class="badge bg-success fs-5 text-wrap mb-2">Завершена</div>
            {% endif %}
        </div>
                <div class="col-4 text-end">
            <div class="badge bg-secondary fs-5 text-wrap" style="width: 20rem;">{{ object.get_frequency_display }}
            </div>
            <div class="btn-group mt-2">
                <div class="btn-group">
                    {% if user == object.author %}
                    <a href="{% url 'mailing:edit' object.pk %}" type="button"
                       class="btn btn-outline-primary">Редактировать</a>
                    <a href="{% url 'products:delete' object.pk %}" type="button"
                       class="btn btn-outline-danger">Удалить</a>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="w-100">
            <div class="col-4">
                <h4 class="text-body-secondary">{{ object.time }}</h4>
            </div>
        </div>
        <div class="col-4"></div>
    </div>
    <div id="newsletter-status">
    <p>Status: {{ object.get_status_display }}</p>
    {% if user.is_authenticated and object.status in allowed_statuses %}
        <button id="start-newsletter" class="btn btn-primary">Сменить статус</button>
        <script>
            const toggleButton = document.getElementById("start-newsletter");
            toggleButton.addEventListener("click", function(event) {
                fetch("{% url 'mailing:start_newsletter' object.pk %}", {
                    method: "POST",
                    headers: {
                        "X-CSRFToken": "{{ csrf_token }}",
                    },
                })
                .then(response => response.json())
                .then(data => {
                    const newsletterStatus = document.getElementById("newsletter-status");
                    newsletterStatus.innerHTML = "<p>Status: " + data.status + "</p>";
                    toggleButton.textContent = (data.status === "ST") ? "Stop Newsletter" : "Start Newsletter";
                    location.reload();
                });
            });
        </script>
    {% endif %}
</div>
</div>
<div class="container">
    <div class="header">
        <h3 class="text"> Сообщение</h3>
    </div>
    <p class="fs-5"> {{ object.message.body }} </p>
    <div class="footer">
        <p class="fs-5 text-secondary"> Автор: {{ object.author.first_name }} {{ object.author.last_name }} ({{
            object.author.email }})</p>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/newsletter/newsletter_form.html
{% extends 'main/base.html' %}
{% load media_tags %}
{% load custom_filters %}
{% block content %}

<section class="text-center container">
    <div class="row py-lg-5">
        <div class="col-md-8 mx-auto">
            <h1 class="fw-light">{{ title }}</h1>
        </div>
    </div>
</section>
<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    {% if object %}
                    <div class="card-header">Редактирование рассылки</div>
                    {% else %}
                    <div class="card-header">Создание рассылки</div>
                    {% endif %}
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            Клиенты:
                            <div class="mb-2"> {{ form.client }}</div>
                            Время рассылки:
                            <div class="mb-2"> {{ form.time }}</div>
                            Сообщение:
                            <div class="col mb-2"> {{ form.message }}
                                <a href="{% url 'mailing:message_create' %}" class="col-4 btn btn-secondary mt-2">Создать сообщение</a>
                            </div>
                            Частота рассылки:
                            <div class="mb-2"> {{ form.frequency }}</div>
                            <button type="submit" class="btn btn-success">
                                {% if object %}
                                Сохранить
                                {% else %}
                                Создать
                                {% endif %}
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/newsletter/newsletter_list.html
{% extends 'main/base.html' %}
{% load media_tags %}
{% load custom_filters %}
{% block content %}
<section class="text-center container">
    <div class="row py-lg-5">
        <div class="col-md-9 mx-auto">
            <h1 class="fw-light">{{ title }}</h1>
            <p>Добро пожаловать в наш cервис рассылки.</p>
            <p>Здесь вы можете создать рассылку.</p>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <h5>Количество рассылок: {{ total_mailings }}</h5>
            <h5>Количество активных рассылок: {{ active_mailings }}</h5>
            <h5>Количество уникальных клиентов: {{ unique_clients }}</h5>
        </div>
        <div class="col-9 ms-3">
            <h4>Случайные статьи из блога:</h4>
            {% for article in random_articles %}
            <h5><a>{{ article.title }}</a></h5>
            <p>{{ article.content }}</p>
            {% endfor %}
        </div>
    </div>
</section>

<div class="album py-5 bg-light">
    <div class="container">
        <div class="col-12 mb-5">
            {% if user.is_moderator %}
            <a class="btn btn-secondary" href="#">Добавить рассылку</a>
            {% else %}
            <a class="btn btn-primary" href="{% url 'mailing:create' %}">Добавить рассылку</a>
            {% endif %}
            <a class="btn btn-outline-secondary" href="{% url 'mailing:client_list' %}">Список клиентов</a>
            <a class="btn btn-outline-secondary" href="{% url 'mailing:message_list' %}">Список сообщений</a>
        </div>
        <div class="row justify-content-center">
            {% for object in object_list %}
            {% if user.is_staff or user == object.author %}
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <div class="card-body">
                        <h4><a href="{% url 'mailing:newsletter' object.pk %}" class="card-title">{{ object.message.subject }}</a>
                        </h4>
                        <div class="card-text">
                            {% for client in object.client.all %}
                            <p style="column-width: 30%; column-count: 2; column-fill: balance;">{{ client.email }}</p>
                            {% endfor %}
                        </div>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="col">
                                <h6 class="card-subtitle mb-3 text-body-secondary">{{ object.get_frequency_display }} (в {{ object.time }})</h6>
                                <div class="btn-group">
                                    {% if user == object.author  %}
                                    <a href="{% url 'mailing:edit' object.pk %}" type="button"
                                       class="btn btn-sm btn-outline-primary">Редактировать</a>
                                    <a href="{% url 'mailing:delete' object.pk %}" type="button"
                                       class="btn btn-sm btn-outline-danger">Удалить</a>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endif %}
            {% endfor %}
        </div>

    </div>

</div>
{% endblock %}